name: A job in my workflow
on:
  workflow_call:
    inputs:
      target-env:
        description: 'Environment to deploy'
        type: string
        required: true
      source-branch:
        description: 'Branch used to deploy'
        type: string
        required: true
        default: main
jobs:
  say-hello:
    name: Deploy to ${{ inputs.target-env }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Env ${{ inputs.target-env }}, branch ${{ inputs.source-branch }}"
      - uses: actions/checkout@v3
      - run: cat ./random-file
