name: Greeting Action
on:
  workflow_call:
    inputs:
      target-env:
        description: 'Environment to deploy'
        type: string
        required: true
      source-branch:
        description: 'Branch used to deploy'
        type: string
        required: true
        default: main
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Env ${{ inputs.target-env }}, branch ${{ inputs.source-branch }}"
